### ISSUE TITLE
Docs : Add a CONTRIBUTING.md file with contribution guidelines.

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#1]
Add a CONTRIBUTING.md file with a detailed explanation of how a new user can use and contribute to the repository.

It should include -
1. Setting up the project locally guide.
2. Github workflow of cloning, forking, adding upstream, separate branches, etc.
3. Procedure to make a PR.

**Comment by Mambinge** [comment]
@janvi01 I can work on this one.

**Comment by janvi01** [comment]
Sure @Mambinge I have assigned you. For any doubts, drop in the comments here or dm me over Discord.
