### ISSUE TITLE
Fix: Mobile responsiveness for Query Output header

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#10]
**Describe the bug**
Currently, the query output header(Query output text, query time, export csv) is not responsive in mobile view.

**To Reproduce**
1. Go to https://sql-editor-online.vercel.app/
2. Switch to Mobile view.
3. Run a Query and scroll down to Query output.

**Expected behavior**
It should be responsive.

**Screenshots**
<img width="530" alt="Screenshot 2023-10-12 at 12 24 27 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/890f9f59-64bd-43dc-b331-33b31eb9a050">

**Comment by killerkc12** [comment]
I would like to work on this. Please assign to me

**Comment by 227001** [comment]
@janvi01 I have already completed this fix and submitted PR. The modified page is displayed as follows:
![截图18](https://github.com/janvi01/sql-editor/assets/145539206/363d3ad7-ded7-4949-9536-dfb1a0ae317e)
![截图19](https://github.com/janvi01/sql-editor/assets/145539206/324eb450-db5c-4c76-ad3a-dc84b6309d77)

**Comment by 227001** [comment]
I have completed this task and submitted PR. The modified page is displayed as follows:
![截图18](https://github.com/janvi01/sql-editor/assets/145539206/6620fcfa-631c-403a-8065-169f21637695)
![截图19](https://github.com/janvi01/sql-editor/assets/145539206/64fdff1d-d8a2-487e-8760-2c65897e4af4)

**Comment by prash240303** [comment]
hi @janvi01  , UI design based issues are being accepted? I found many UI design issues that needs to be resolved and i can work on them , so if yes may i create a issue listing all those issues and work on that ?

**Comment by janvi01** [comment]
Hello @prash240303 please create new issues, kindly recheck before creating if the issue ticket already exist or not to avoid duplicates.
