### ISSUE TITLE
Docs: enhance readme, add Community and Contributions section

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#14]
Recently, we have added our Contributing.md file that guides a user on how to contribute. Add a section in the README.md named "Community and Contributions" that references the user to the contributing guidelines. Also, list all the contributors to the project in this section.

Example - 
<img width="1792" alt="Screenshot 2023-10-13 at 8 37 05 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/28349c2a-0849-4251-bc5f-95e04a2986f2">

**Comment by Freakyab** [comment]
can you assign it to me !
