### ISSUE TITLE
Feat: add a functionality to export result in JSON format

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#15]
**Is your feature request related to a problem? Please describe.**
Currently, after running a query we can export results in the CSV format.

**Describe the solution you'd like**
- Add a way to export results in JSON files.
- Add a button the same as 'Export CSV' as 'Export JSON'

<img width="448" alt="Screenshot 2023-10-13 at 8 41 08 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/15de5cc4-d1d5-4d43-aef3-dd250e1b7c2b">

**Comment by janvi01** [comment]
> can you assign it to me !

Following the rule of single issue to a contributor at a time.

**Comment by janvi01** [comment]
Hey @Freakyab now you can work on this issue.

**Comment by janvi01** [comment]
@Freakyab any updates?

**Comment by Freakyab** [comment]
Currently I am busy in my college work, I will try to complete it later, or otherwise , you can unassign me.

**Comment by prash240303** [comment]
i would like to work on this issue , can u assign this issue to me?

**Comment by janvi01** [comment]
assigned @prash240303

**Comment by sonvir249** [comment]
@janvi01 I have raised a PR for this issue. Please review - https://github.com/janvi01/sql-editor/pull/29

**Comment by janvi01** [comment]
@sonvir249 Kindly comment on the issue before creating a PR.

**Comment by sonvir249** [comment]
> Kindly comment on the issue before creating a PR.

@janvi01  I apologize for not commenting on the issue before creating the PR. I'll make sure to follow this process moving forward. If you have any specific comments or suggestions regarding the PR, please feel free to let me know. Thanks again!

**Comment by janvi01** [comment]
@sonvir249 The PR is already there by the assignee. You can look at any other issue.
