### ISSUE TITLE
Docs: Add a CODE_OF_CONDUCT.md with guidelines

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#18]
When working on a certain open-source project, every participant should understand what is expected of them. That is where a code of conduct comes in. This is a document that outlines the rules that the participants in the open-source community should follow.

Create a new file named CODE_OF_CONDUCT and add guidelines.

Take reference from -

1. React - https://github.com/facebook/react/blob/main/CODE_OF_CONDUCT.md
2. Google - https://opensource.google/conduct
3. https://contributing.md/your-code-of-conduct-for-open-source-communities/

**Comment by sriharsh05** [comment]
I want to work on this issue. Please assign it to me.

**Comment by janvi01** [comment]
assigned @sriharsh05 feel free to drop in any doubts

**Comment by sriharsh05** [comment]
You just want the code of conduct to contribute to your repositories right? Or do you want it to be specific to this repo?

**Comment by janvi01** [comment]
Please go through the reference links and [this PR](https://github.com/janvi01/sql-editor/pull/19).


> You just want the code of conduct to contribute to your repositories right? Or do you want it to be specific to this repo?
