### ISSUE TITLE
Redesign and implement Queries History card

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#2]
**Is your feature request related to a problem? Please describe.**
Currently, the queries history card is not well-designed.

**Describe the solution you'd like**
Reimplement query history cards with an improved design that enhances user experience.

<img width="652" alt="Screenshot 2023-10-02 at 5 14 59 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/dbee3d9e-2dff-4fb8-96d1-90841f593661">

**Comment by Piyush07p** [comment]
Can you assign this to me

**Comment by janvi01** [comment]
Go ahead @Piyush07p

**Comment by prash240303** [comment]
i think this issue has already been resolved and can be closed

**Comment by Aditya-Armal** [comment]
@janvi01 is this issue closed? I am willing to redesign the history card.

**Comment by janvi01** [comment]
@aditya-armal Please propose your design first here in the comments, how you plan to redesign it.
