### ISSUE TITLE
Improve readme by adding badges

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#21]
Currently, the readme looks average with no styling and attraction for users.

Revamp the readme introduction part by adding different badges.

For Example - Take a reference from the [react-play](https://github.com/reactplay/react-play#reactplayrepo-react-play) repo. Use sql editor favicon icon

<img width="899" alt="Screenshot 2023-10-18 at 11 31 41 AM" src="https://github.com/janvi01/sql-editor/assets/34344234/5b97ed90-a428-4c7d-accb-a17ce515577a">

**Comment by Subhashini014** [comment]
Could you please assign me this isssue.

**Comment by janvi01** [comment]
assigned @Subhashini014 feel free to drop in any doubts.

**Comment by janvi01** [comment]
@Subhashini014 any updates?

**Comment by prash240303** [comment]
Hi , may i work on this issue ?

**Comment by janvi01** [comment]
@prash240303 The project follows one contributor-one issue at a time rule.

**Comment by janvi01** [comment]
@prash240303 you can take this up now.
