### ISSUE TITLE
Feat: add footer

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#22]
**Is your feature request related to a problem? Please describe.**
Add a Footer section that includes -
- copyrights - "SQL Online Editor - Copyright ©2023"
- the creator's GitHub profile - https://github.com/janvi01
- "Found an issue? Report it [here](https://github.com/janvi01/sql-editor/issues/new/choose)"

Take reference from other open-source projects like https://reactplay.io/

**Comment by Ferdinand-Ogama** [comment]
Hello @janvi01, please assign me this issue.

**Comment by janvi01** [comment]
assigned @Ferdinand-Ogama feel free to drop in any doubts.

**Comment by Ferdinand-Ogama** [comment]
Ok.

**Comment by Ferdinand-Ogama** [comment]
@janvi01 I can seem to find the hex code green version of the Navbar to also use in the footer. I have tried inspecting elements, but I still can't find. 
Do you have a way of doing it? 

Apologies, I am new to Web and React, but I will deliver :)

**Comment by Ferdinand-Ogama** [comment]
Of course with your guidance.

**Comment by Ferdinand-Ogama** [comment]
I found it. It's teal

**Comment by Ferdinand-Ogama** [comment]
Hello, I get fatal errors whenever I try to commit. Not sure where the problem is? Can't find solutions online. Will Keep trying.

**Comment by janvi01** [comment]
@Ferdinand-Ogama What errors are you getting?

**Comment by Ferdinand-Ogama** [comment]
I resolved it. Sent a PR.

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by 08Uzair** [comment]
Please Can you assign this to me

**Comment by janvi01** [comment]
Hey @tutrinh16 @08Uzair this issue is already assigned. Please take a look at other issues in the issue section.

**Comment by Ferdinand-Ogama** [comment]
@janvi01 created a PR for this issue 3 days ago. Care to look at it?

**Comment by janvi01** [comment]
Sure @Ferdinand-Ogama I'll look when I can, quite busy with some other task.
