### ISSUE TITLE
Fix: responsiveness for Query History

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#24]
**Describe the bug**
Currently, we have added a functionality to delete a single history but the icons are not aligned, it is not responsive.

**To Reproduce**
1. Go to https://sql-editor-online.vercel.app/
2. Click on Run Query.
3. See Query history container.

**Expected behavior**
Align the elements properly, fix the height, add a vertical scrollbar, and make it responsive for all screens.

**Screenshots**
<img width="690" alt="Screenshot 2023-10-19 at 12 25 11 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/3c89d8f7-6ede-4ccf-8b83-da6249002963">

**Comment by killerkc12** [comment]
@janvi01 I would like to work on this

**Comment by janvi01** [comment]
sure, go ahead @killerkc12

**Comment by janvi01** [comment]
@killerkc12 any updates?

**Comment by killerkc12** [comment]
@janvi01 I have started doing the chages but not completed yet because of some personal reason. By tomorrow I will try to complete.

**Comment by killerkc12** [comment]
@janvi01 Please review the attached PR
![image](https://github.com/janvi01/sql-editor/assets/50802786/ef6bed92-1f4a-406c-bf23-b67001c1a491)
![image](https://github.com/janvi01/sql-editor/assets/50802786/f95c5cb4-7476-4dcd-8062-e5e421f4ba5d)
