### ISSUE TITLE
Spacing between Queries History and Delete button is not consistent 

### ISSUE THREAD

**Issue by Tajinder-Dhoot** [janvi01/sql-editor#27]
**Describe the bug**
There are 2 issues with the alignment of Delete buttons:
1. Delete button touches the text in Queries History section. There should be some spacing (reproducible when screen width > 1428px)
2. Delete buttons are not in alignment if there are more than one text query in history.

**To Reproduce**
1. Go to 'https://sql-editor-i8d6w7vvc-janvi01.vercel.app'.
2. Run the query using a table name (Click on 'Available Tables' button to see table names).
3. Run another query with another table name of different length (eg. Customers and Products).
4. See error: Delete button are too close to the text and not aligned with consistent spacing. (When screen width is > 1428px)

**Expected behavior**
There should be a consistent spacing between text and delete buttons. My suggested is to right align the delete button with some right margin.

**Screenshots**
![image](https://github.com/janvi01/sql-editor/assets/38849429/4fd961ed-0146-4848-b9c1-ac50da70d7ec)

**Desktop**
 - OS: Windows 10
 - Browse: Chrome, Edge, Mozilla
 - Chrome Version [118.0.5993.89]
 - Screen width: bug is reproducible when screen width > 1428px

**Comment by Tajinder-Dhoot** [comment]
@janvi01 I would like to work on this.

**Comment by janvi01** [comment]
Hey @Tajinder-Dhoot Thanks for opening the issue but this issue is already being addressed in another [issue ticket](https://github.com/janvi01/sql-editor/issues/24). You may want to leave a comment there if there are no updates.
