### ISSUE TITLE
Results are not displayed when user runs the query 2nd time.

### ISSUE THREAD

**Issue by Tajinder-Dhoot** [janvi01/sql-editor#28]
**Describe the bug**
When user runs the query 1st time, the results are displayed. But when user runs the query 2nd time, the results are not displayed and loader keeps spinning.

**To Reproduce**
1. Go to 'https://sql-editor-i8d6w7vvc-janvi01.vercel.app/'
2. Click on 'Run Query' button > Results would be displayed.
3. Click on 'Run Query' button again > This time, results are not displayed, but loader keeps spinning.

**Expected behavior**
Results should be displayed every time the query is run by user.

**Screenshots**
When user runs the query 1st time.
![image](https://github.com/janvi01/sql-editor/assets/38849429/40ac0e72-7473-4a33-b3c4-cdf3b9983d33)

When user runs the query 2nd time.
![image](https://github.com/janvi01/sql-editor/assets/38849429/c41b75e4-7b05-4867-a0db-e804cf2c0439)

**Desktop**

OS: Windows 10
Browse: Chrome, Edge, Mozilla
Chrome Version [118.0.5993.89]
Screen width: bug is reproducible when screen width > 1428px

**Comment by janvi01** [comment]
Hey @Tajinder-Dhoot Thanks for opening the issue. Do you want to work on this?

**Comment by Tajinder-Dhoot** [comment]
Yes, I would like to - @janvi01 

> Hey @Tajinder-Dhoot Thanks for opening the issue. Do you want to work on this?

**Comment by Tajinder-Dhoot** [comment]
@janvi01 - can you please assign this to me?

**Comment by janvi01** [comment]
assigned @Tajinder-Dhoot feel free to drop in any doubts.
