### ISSUE TITLE
UI bug : mobile view

### ISSUE THREAD

**Issue by prash240303** [janvi01/sql-editor#30]
**Describe the bug**
content overflow of query time container in mobile view

**To Reproduce**

    Go to https://sql-editor-online.vercel.app/
    Click on Run Query.
    See Query time container.

Expected behavior
 fix the width of the element and add proper padding . maybe a column view is needed for the content for better spacing .

![WhatsApp Image 2023-10-24 at 09 39 45](https://github.com/janvi01/sql-editor/assets/93905743/35aa5dc5-33a7-45d2-b11b-e52870e3cbda)

**Comment by janvi01** [comment]
Hey @prash240303 Thanks for opening the issue. The issue is already being addressed [here](https://github.com/janvi01/sql-editor/issues/10). If there are no updates on that, you can take it up.
