### ISSUE TITLE
Fix: reposition query time box and responsiveness 

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#34]
**Describe the bug**
The query time box isn't appropriately positioned right now. 

**To Reproduce**
1. Go to https://sql-editor-online.vercel.app/
2. Run a query.

**Expected behavior**
Align the 'Query took' box below the `Export JSON` button and make it responsive for all screens.

**Screenshots**
Current large screen view -
<img width="1792" alt="Screenshot 2023-10-27 at 11 28 35 AM" src="https://github.com/janvi01/sql-editor/assets/34344234/f1082dec-ce28-4f6c-be9e-c31143c8ab4e">

mobile view -
<img width="400" alt="Screenshot 2023-10-27 at 11 28 54 AM" src="https://github.com/janvi01/sql-editor/assets/34344234/14cba2ef-54f9-4387-a2fa-c46a09c3fc19">

**Comment by Piyush07p** [comment]
can you assign me this
