### ISSUE TITLE
Feat: Add a Toast component that appears after running a query

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#37]
**Is your feature request related to a problem? Please describe.**
Currently, when clicking on the run query, the spinner loads, and the result is displayed.

**Describe the solution you'd like**
Add a toast component saying "Query run successful" that appears at the bottom after a query is being run and disappears when results are displayed.

Take reference from the [Chakra Toast component.](https://chakra-ui.com/docs/components/toast).

**Comment by prash240303** [comment]
i would like to work on this issue , can u assign the same to me ?

**Comment by prash240303** [comment]
hi @janvi01 can u assign the issue to me ?
