### ISSUE TITLE
Query results always show results for CUSTOMERS table.

### ISSUE THREAD

**Issue by Tajinder-Dhoot** [janvi01/sql-editor#41]
**Describe the bug**
There are 2 scenarios to reproduce this bug:
1. User runs query for other tables e.g. Categories, Products or Suppliers. But SQL web app always display results for Customers.
2. User runs query with invalid table name. But SQL web app display results for Customers table.

**To Reproduce**
1. Go to 'https://sql-editor-i8d6w7vvc-janvi01.vercel.app/'
2. Enter query 'select * from CATEGORIES'
3. Click on 'Run Query' button > Results are displayed for Customers table.
4. Enter query 'select * from CATEGO'
5. Click on 'Run Query' button > Results are displayed for Customers table.

**Expected behavior**
For scenario 1:
SQL web app must display results for specific table in query.

For scenario 2:
SQL web app must display error message.

**Screenshots**
The column names in screenshot should be categoryId, categoryName, description, picture.

<img width="1447" alt="results always for customers table" src="https://github.com/janvi01/sql-editor/assets/38849429/e852f8ea-c077-42e6-a8cf-cdad8653a934">

**Desktop (please complete the following information):**
- OS: Windows 10
- Browse: Chrome, Edge, Mozilla
- Chrome Version [118.0.5993.89]

**Comment by Tajinder-Dhoot** [comment]
@janvi01 I have the solution ready for PR if its is assigned to me.

**Comment by janvi01** [comment]
Hey @Tajinder-Dhoot Thanks for opening the issue. I am not able to reproduce scenario 1. Please can you check once again.

The issue is valid for scenario 2.
