### ISSUE TITLE
Bug: Executing same query multiple times should not be added to query History is previously same query is executed.

### ISSUE THREAD

**Issue by aditya-armal** [janvi01/sql-editor#48]
**Describe the bug**
Executing the same query results in it being added to the query history, even though it should not be added if the previous query executed was the same.

**To Reproduce**
1. Execute a query.
2. Execute the same query again.

**Expected behavior**
The same query should not be added to the query history if it was the previous query is executed.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
- Operating System: Windows 10
- Browser: Chrome, Firefox
- Browser Version: 1.61.101

**Additional context**
N.A.

**Comment by aditya-armal** [comment]
I have the Solution Ready.

**Comment by janvi01** [comment]
Go ahead @aditya-armal

**Comment by aditya-armal** [comment]
@janvi01 can you please review this PR.
