### ISSUE TITLE
Bug: executed query is appended to the end of the query history

### ISSUE THREAD

**Issue by aditya-armal** [janvi01/sql-editor#51]
**Describe the bug**
The recently executed query is appended to the end of the query history, which should be displayed at the top instead of the last position in the query history.

**To Reproduce**
-Execute a query.
-Execute another query.
-Observe the position of the last executed query in the query history.

**Expected behavior**
The recently executed query should be displayed at the top of the query history.

**Screenshots**
N.A

**Desktop (please complete the following information):**
 - Operating System: Windows 10
-Browser: Chrome, Firefox
-Browser Version: 1.61.101

**Additional context**
N.A

**Comment by aditya-armal** [comment]
Assign the Issue, i will raise PR. Solution is Implemented.

**Comment by aditya-armal** [comment]
@janvi01 Do you want this issue to be fixed as described? or should i close it or you need some more clarification.

**Comment by prash240303** [comment]
sure , work on the issue and raise a PR for the following

**Comment by amanswarnakar** [comment]
Hey @janvi01 @prash240303, please assign this issue to me under JWOC'24.

**Comment by prash240303** [comment]
Sure

**Comment by prash240303** [comment]
do let me know on discord , tag me the issue and when u have the PR ready

**Comment by amanswarnakar** [comment]
@prash240303 @janvi01 I have created a pull request. Please check once.
