### ISSUE TITLE
[BUG] Inconsistent Background Color for 'Select Theme' Button

### ISSUE THREAD

**Issue by aditya-armal** [janvi01/sql-editor#56]
**Describe the bug:**
The "Select Theme" button is currently utilizing the same background color as the website background, resulting in visual inconsistency and making the button less noticeable.

**To Reproduce:**

- Navigate to the homepage.
- Locate the "Select Theme" button.
- Observe the background color of the button.

**Expected behavior**
The "Select Theme" button should have a distinct background color that differs from the website background, ensuring it stands out and aligns with the theme selection feature.

**ScreenShots**

**Current UI**

![Screenshot 2023-12-30 220530](https://github.com/janvi01/sql-editor/assets/20648225/252d37f7-9c58-4782-8106-c7a9b13f5fbd)

**Proposed UI**

![Screenshot 2023-12-30 220503](https://github.com/janvi01/sql-editor/assets/20648225/9c5261cb-38f4-40a7-8439-96ca93f24e74)

I have the implementation ready, If it aligns with the project requirement assign me this issue, will raise PR.

**Comment by prash240303** [comment]
Hey, @aditya-armal , The UI will be updated soon with a better design, so UI-related issues are ignored for now. If you find any feature issues, then you are welcome to create a new issue.
