### ISSUE TITLE
Reimplement empty state below editor

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#6]
**Is your feature request related to a problem? Please describe.**
Currently, when there is no query run, it shows "Nothing to show at the moment" which looks boring.

**Describe the solution you'd like**
Reimplement the empty area with an image addition and text shown below.

![emptystatereimplement](https://github.com/janvi01/sql-editor/assets/34344234/20268496-fed4-4337-b255-806e0af68a88)

png file - 
![illustration](https://github.com/janvi01/sql-editor/assets/34344234/55ce5cd4-2849-4541-8557-7f3a9e7c6ced)

The upper div will expand up to the illustration.

**Comment by Yogeshp0012** [comment]
Hi @janvi01 , Can i work on this?

**Comment by janvi01** [comment]
Hey @Yogeshp0012 Sure, I have assigned you. Feel free to ask any doubts.

**Comment by Yogeshp0012** [comment]
![image](https://github.com/janvi01/sql-editor/assets/54975573/4d3684e9-4084-4b39-a34d-123ed1c82645)

Is this fine @janvi01

**Comment by janvi01** [comment]
> ![image](https://user-images.githubusercontent.com/54975573/274008285-4d3684e9-4084-4b39-a34d-123ed1c82645.png)
> 
> Is this fine @janvi01

Yeah, looks good. Kindly create a PR. Thanks.
