### ISSUE TITLE
Add a button to import data file from user's pc

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#8]
**Is your feature request related to a problem? Please describe.**
Just like the result can be exported in CSV format in our web app now, there should be a way to import data also.

**Describe the solution you'd like**
Add an import button that on clicks prompts the user to their local files. The styling would be the same as the export button and needs to be added below the editor beside the `available tables` button. There is no need to add further functionality, just UI as of now.

Add a button having an icon and "Import" that on clicks prompts the user to their local files.

<img width="1792" alt="Screenshot 2023-10-11 at 11 11 12 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/711d53ab-5878-44fe-950a-083e45a411a9">

**Comment by Yogeshp0012** [comment]
Can I work on this?

**Comment by janvi01** [comment]
Yes, @Yogeshp0012 assigned.
