### ISSUE TITLE
Feat: Add a single history delete functionality

### ISSUE THREAD

**Issue by janvi01** [janvi01/sql-editor#9]
**Is your feature request related to a problem? Please describe.**
Currently, the user is able to delete all history at once. There should be a way to delete a single history at a time.

<img width="604" alt="Screenshot 2023-10-12 at 12 20 45 PM" src="https://github.com/janvi01/sql-editor/assets/34344234/4dbae982-35f5-48b4-ac5b-9105580636cc">

**Describe the solution you'd like**
Add a delete button beside each history row and onclick it should delete that particular history. This can be done using a map and assigning a unique key to every history.

**Comment by killerkc12** [comment]
@janvi01 I like to work on this. Please assign to me

**Comment by janvi01** [comment]
Assigned @killerkc12 feel free to ask any doubts.

**Comment by killerkc12** [comment]
@janvi01 #12 Kindly review the PR
